### ISSUE TITLE
How did you customize the clock ?

### ISSUE THREAD

**Issue by NicolasDesjobert** [2hdlockness/MMM-IronManGIF#1]
Hi was wondering if you could show your custom.css file, i would love to customize the clock like you did, or if anyone knows how it could be done. thanks in advance :)

**Comment by 2hdlockness** [comment]
Hello
Sorry for the late response but I'm in the middle of a move right now so not much time ...
Here are my custom.css settings:
.module.clock {
  margin-bottom: 100px;
}
.MMM-IronManGIF {
  margin-bottom: -364px;
}
Perhaps it will be necessary to adapt for your configuration ...
