### ISSUE TITLE
Image size?

### ISSUE THREAD

**Issue by ariley** [2hdlockness/MMM-IronManGIF#3]
Hi,

I love this mdule.

I set #7 to 200% but it didn't seem to get larger. Can I only go to 100?

**Comment by 2hdlockness** [comment]
Hello
Thank you for your interest in my module.
The maximum size is obtained by setting the value maxWith: 100%
The gif intentionally cannot be larger because it would be too pixelated.
The size 100% corresponding to the original gif.
